Feature/alc 26/game instance
Thalassa666/Alchemica pull request #15
Opened 2024-09-03 15:33 UTC by RanelGM

### Какую задачу решаем
Создаёт механику игры на Canvas API. Добавлены:
- логика коллизий для границ игры / предметов
- логика передвижения и взаимодействия персонажа с объектами
- логика выбора ингредиентов и создания предметов
- модуль уведомлений
- константы для дальнейшего расширения игры

### TBD (если есть)
- книга рецептов
- логика запуска/завершения игры

2024-09-05 11:38 UTC, Gyxer513 requested changes
Проделана большая работа, механика игры работает корректно. 

Хорошая идея вынести механику игры в отельную папку.  Понравилась логика работы хуков. 

Есть небольшое косметические замечания по импортам в коде.

2024-09-05 11:38 UTC, Gyxer513 commented on packages/client/src/game/types/types.ts
> +  key: string
несколько ключей в типах повторяются, тут лучше воспользоваться наследованием или расширением существующего.

2024-09-05 11:38 UTC, Gyxer513 commented on packages/client/src/game/ui/GameClient.tsx
> +import { useCraftDialog } from '../hooks/useCraftDialog'
Давай все хуки будем импортировать из одного места.

Например так

```
import {useCraftGialog, useGameState... } from '@game/hooks'
```

Или можно импортировать сразу все хуки через *, так будет гораздо компактнее.

2024-09-05 18:33 UTC, RanelGM commented on packages/client/src/game/types/types.ts
> +  key: string
Подскажи, пожалуйста, а какие повторения хотим убрать? 

Выделен кусок с ConditionType - это типизация значения объекта ConditionNames, который объявлен через "const assertions". По факту, это альтернатива enum, которая типизирует точечные значения объекта, но при этом его не обязательно передавать как enum ссылку

Если повторения с typeof ConditionNames и keyof typeof ConditionNames, то так получаются значения из объекта, т.к. keyof у TS есть, а вот valueOf нет. Но могу предложить создать дженерик, который будет имплементировать valueOf если нужно

2024-09-05 18:43 UTC, Gyxer513 commented on packages/client/src/game/types/types.ts
> +  key: string
Например так 

```
type TKeyType = {
  key: string
}


export interface CraftTool  extends TKeyType{
  label: string
  imgSrc: string
  comboCount: number
  collision: Collision
  toConditions: Record<string, boolean>
}
```

Так можно не дублировать key во всех типах и подобные ему.

2024-09-05 18:45 UTC, RanelGM commented on packages/client/src/game/types/types.ts
> +  key: string
Да, извини, что пинганул - только потом понял, что на другую строку был комментарий, и понял о чём речь)

2024-09-05 18:49 UTC, Gyxer513 commented on packages/client/src/game/types/types.ts
> +  key: string
А можно еще объединением сделать 
```
// Общий тип
export type ItemBase = {
  key: string
  type: CraftType
}


// Тип для предметов инвентаря
export type InventoryItem = ItemBase & {
  imgSrc: string
  condition: ConditionType
  label: string
}
```

2024-09-05 18:51 UTC, Gyxer513 commented on packages/client/src/game/types/types.ts
> +  key: string
на самом деле я вроде ту строчку выбрал, но подцепилась не та. 

Извини за духоту если что)

2024-09-05 19:09 UTC, RanelGM commented on packages/client/src/game/types/types.ts
> +  key: string
Всё ок, я согласен тут. Если что, то вынес ItemBase через amend и force push

2024-09-05 19:16 UTC, Gyxer513 approved these changes
Отличная работа,  у меня больше нет замечаний. 

Так держать!

2024-09-06 06:10 UTC, kyzinatra commented on packages/client/src/core/helpers/groupArray.ts
> +    }
Круто, что вы выносите логику в отдельные файлы

2024-09-06 06:13 UTC, kyzinatra commented on packages/client/src/core/utils/constants.ts
> +  ArrowDown: 'ArrowDown',
Мне кажется коды стоит называть в соответствии с их предназначением, а не названием клавиши. К примеру

```js

export const EvtCodes = {
    moveUp: ["KeyW", "ArrowUp"],
    exit: ["Escape"],
    ...
}
```

Так можно и несколько клавиш на 1 действие назначать, и логика более понятна

2024-09-06 06:14 UTC, kyzinatra commented on packages/client/src/game/constants/craftTools.ts
> +  DialogWidth: 1024,
Понравилось, что вы выносите все в константы

2024-09-06 06:15 UTC, kyzinatra commented on packages/client/src/game/hooks/useGameBorders.ts
> +    checkForNearBorder,
Хорошая декомпозиция хуков состояния игры

2024-09-06 06:16 UTC, kyzinatra commented on packages/client/src/game/hooks/useGameState.ts
> +  notifications = defaultState.notifications
Мне кажется эти данные лучше сделать приватными

2024-09-06 06:20 UTC, kyzinatra approved these changes
Отличная работа! Выбрана интересная концепция, распределить логику игры в отдельные хуки. В данном случае внимательно нужно следить за тем, чтобы не перегружать хуки и вовремя их разбивать. И у вас хорошо это получается. Хоть, по моему мнению, логика игры это одна из самых сложных частей проекта, вы отлично с ней справились! 
Понравилось, что вы вынесли все по отдельным константам и не стали хардкодить такие значения. 
Также отмечу хорошее ревью ваших коллег. 
Я принимаю вашу работу, желаю вам успехов в дальнейшем обучении!

2024-09-06 10:52 UTC, merged