Feature/alc 17/forum
Thalassa666/Alchemica pull request #21
Opened 2024-09-08 16:33 UTC by Thalassa666

### Какую задачу решаем
Вёрстка страницы форума
- разделы форума слева в списке в виде дропдаунов
- при нажатии на тему в разделе открывается справа модалка со всеми сообщениями
- есть кнопки добавления сообщений и новых тем
- сделала пару констант для стилей
(апи будет в 8 спринте)

2024-09-08 17:16 UTC, RanelGM requested changes
Проделана очень отличная работа, отдельно отмечаю отличные навыки по декомпозиции и умению разбивать на логические блоки, что очень здорово. Выглядит и читается всё отлично

Есть 1 важный момент с useEffect, который я предложил бы поправить, а прочие моменты - по желанию

2024-09-08 17:16 UTC, RanelGM commented on packages/client/src/components/forum/ForumList.tsx
> +                <div>нет тем</div>
Отлично, что продумана ситуация, когда тем не будет! Пользователь не будет гадать почему тут пусто

2024-09-08 17:16 UTC, RanelGM commented on packages/client/src/components/forum/styles.module.scss
> +  color: var(--gray-color);
Отлично, что цвета вынесены в переменные

2024-09-08 17:16 UTC, RanelGM commented on packages/client/src/components/forum/styles.module.scss
> +  font-family: 'Bookman Old Style', sans-serif;
Я рекомендовал бы шрифты тоже вынести в переменные. Очень легко можно будет допустить ошибку при перечислении семейства в других местах
А в переменной можно было бы заложить что-то вроде --font-family-primary и --font-family-secondary (работает в 90% случаев, когда шрифтов на проекте 1-2) или --font-family-Bookman (когда шрифтов на проекте очень много)

2024-09-08 17:16 UTC, RanelGM commented on packages/client/src/components/forum/Modal.tsx
> +  useEffect(() => {
useEffect, который влияет не на сам компонент, в котором объявлен, а на какие-то другие - опасная штука. Такие стараются держать ближе к началу страницы, чтобы видеть все возможные сайд эффекты. Иначе можно долго искать причину во всех дочерних компонентах

Если хочется очищать url после загрузки страницы, то тогда рекомендую это сделать на самой странице форума (в главном компоненте)
А если хотелось проставлять url в зависимости от клика на топик, то лучше сами топики сделать в качестве Link

2024-09-08 17:16 UTC, RanelGM commented on packages/client/src/components/forum/Modal.tsx
> +  if (!isOpen || !topicContent) return null
Как смотришь на то, чтобы немного поменять подход к рендеру этого компонента? В целом отдавать его на рендер только в том случае, если оно открыто + есть контент. Т.е. это нужно будет сделать првоерку в файле Forum.tsx 

За счёт этого мы сможем убрать пропс isOpen, а все свои действия компонент начнёт выполнять ровно тогда, когда мы и хотим от него

2024-09-08 17:16 UTC, RanelGM commented on packages/client/src/pages/Forum/Forum.tsx
> +            <Modal
isOpen && topicContent && Modal (вот про это я писал в стр. 24 у Modal.tsx)

2024-09-08 18:24 UTC, Thalassa666 commented
внесла правки по ревью

2024-09-08 18:48 UTC, RanelGM approved these changes
Всё хорошо)

2024-09-09 17:37 UTC, kyzinatra commented on packages/client/src/components/forum/ForumList.tsx
> +        </button>
Можно лучше: в `button` нельзя вкладывать `div`. Для того, чтобы проверить свою разметку на валидность используйте https://validator.w3.org/nu/#textarea

2024-09-09 17:38 UTC, kyzinatra commented on packages/client/src/pages/Forum/Layout.tsx
> +    <section className={styles.layout}>
Можно записать `props: PropsWithChildren<OtherProps>`

2024-09-09 17:42 UTC, kyzinatra approved these changes
Отличная работа! Хорошая верстка и стили для форму. Понравилось, что вы выносите в переменные цвета. Из моментов, которые можно улучшить, отмечу, что стоит всю разметку проверить на валидность. Сделать это можно с помощью валидатора w3c, но это не супер критично. Ваша работа принята! Желаю успехов в дальнейшем обучении!

2024-09-10 01:40 UTC, merged