Feature/alc 22/alc 34/profile and redux
Thalassa666/Alchemica pull request #22
Opened 2024-09-10 12:50 UTC by Gyxer513

### Добавлен компонент Profile

Сверстал форму профиля и добавил для нее api в Redux.

-Добавлена форма форма пользователя и смены пароля.
-Добавлено все оставшееся api пользователя - update, updateAvatar, logout, updataPass.
-Добавлена валидация пароля.
-В редаксе создан редьюсер пользователя.
-Доработан кастомных хук useForms, теперь он принимает массив ошибок. 

P.S. Добавил страницу смены пароля, не по макету, но так гораздо удобнее как по мне.

2024-09-10 19:14 UTC, RanelGM requested changes
Проделана огромная работа, отлично расписаны все схемы валидации и подключены к страницам - они работают

Есть небольшие предложения по стилям, в остальном - всё отлично

2024-09-10 19:14 UTC, RanelGM commented on packages/client/src/components/UI/TextButton/styles.module.scss
> +  font-family: 'Lancelot', sans-serif;
По маршруту src/index.css создали файл с  переменной  --lancelot-font 

Лучше заменить на неё и сделать var(--lancelot-font), чтобы каждый раз не писать шрифт и его замену

Там сейчас небольшая ошибка, что не указан рядом sans-serif, но в следующих разом поправить можно будет

2024-09-10 19:14 UTC, RanelGM commented on packages/client/src/components/forms/Layout.tsx
> +        {backgroundClass === 'profileBg' ? (
Предлагаю вынести эту историю в дополнительный пропс isTitleShow

На текущий момент можно использовать тернарник, но если вдруг появится что-то третье и далее - будет очень сложно масштабироваться

А тут можно явно указать пропсом и далее оставить только:
 ```
isTitleShow && (
          <div className={styles.titleOverlay}>
            <h1>ALCHEMIST</h1>
          </div>
)
```

2024-09-10 19:21 UTC, Gyxer513 commented on packages/client/src/components/UI/TextButton/styles.module.scss
> +  font-family: 'Lancelot', sans-serif;
Вообще тут согласен, но только частично, часто в шрифтах используется еще и начертание или размер, например 

```
font-family: 'Lancelot', sans-serif;
font-weight: normal;
```

Для такого предлагаю использовать миксины, это сделает проект еще более масштабируемым. 

Можно использовать миксины для заголовков разных уровней.

2024-09-10 19:25 UTC, RanelGM commented on packages/client/src/components/UI/TextButton/styles.module.scss
> +  font-family: 'Lancelot', sans-serif;
Да, миксины под шрифты тоже отлично заходят - если совсем заморачиваться, то там же можно принимать все шрифтовые опции аргументами

Но у миксинов есть одна большая проблема по сравнению с css переменными: миксины нужно импортировать, а переменные можно указать сразу же (с учетом расширений так ещё и с автодополнением)

По факту - дело вкуса, можно сделать как больше нравится)

2024-09-10 19:37 UTC, Gyxer513 commented
Не стал заморачиваться с миксинами, пошел по простому пути, все поправил.

2024-09-10 19:39 UTC, RanelGM approved these changes
Огонь)

2024-09-11 06:35 UTC, kyzinatra commented on packages/client/src/components/UI/UploadAvatar/UploadAvatar.tsx
> +      }
Можно лучше: пользователи не видят логи. Стоит убрать их из проекта и добавить другой фидбэк

2024-09-11 06:36 UTC, kyzinatra commented on packages/client/src/components/forms/ChangePass.tsx
> +          errorMessage={errors.oldPassword}
Можно лучше: у всех форм стоит заполнить аттрибут `autocomplete` (в реакте  `autoComplete`). Он показывает браузеру как именно следует заполнить это поле. Браузер, при наличии, может сам подставить сюда какую-то информацию. Полный список значений можно посмотреть [тут](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) (https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete)

Самые полезные это: `name` или `given-name` (имя), `nickname`, `email`, `new-password`, `current-password`

2024-09-11 06:37 UTC, kyzinatra commented on packages/client/src/core/api/User.ts
> +    const data = new FormData()
`public` можно не писать

2024-09-11 06:39 UTC, kyzinatra approved these changes
Отличная работа! Вы отлично постарались над формами и страницей профиля. Отметил вам пар моментов для улучшения. В остальном мне все нравится, так что принимаю вашу работу!

2024-09-11 10:31 UTC, merged