Feature/alc 28/game client
Thalassa666/Alchemica pull request #23
Opened 2024-09-10 19:18 UTC by RanelGM

### Какую задачу решаем
Дорабатывает механику игру на Canvas API. Добавлены:
- книга рецептов
- взаимодействия с мышью
- панель быстрого доступа с подсказкой клавиш
- логика запуска/завершения игры
- логика подсчета итогов и редиректа на итоговые страницы

2024-09-10 19:50 UTC, Gyxer513 requested changes
Очень жаль, но работа отклоняется от проверки, ProtectedRoute не дает зайти на страницу игры. 

Можно сделать мердж с моей последней веткой. Был косяк из-за возврата ошибочного слияния.

2024-09-10 20:24 UTC, RanelGM commented
Забрал изменения с последнего ПР. Кол-во файлов для изменения уменьшатся, когда предыдущий зальётся в dev

2024-09-10 20:44 UTC, Gyxer513 requested changes
Отличная работа, пока ты мерджил я ее посмотрел) 

Механика реализована круто, все работает. 

Есть замечание на твое усмотрение. При открытии шпаргалки во время смешивания ингредиентов, шпаргалка закрывает попап со смешиванием, на мой взгляд это не удобно. Можно в этой итерации оставить так, если быстро это не пофиксить. 

Есть предложения по разгрузке главного компонента игры.

2024-09-10 20:44 UTC, Gyxer513 commented on packages/client/src/game/ui/GameClient.tsx
> +export const GameClient: FC<Props> = ({ onGameEnd }) => {
Такую типизацию уже можно не использовать, ревьюер уже давал такие рекомендации. Можно просто так

```
export const GameClient: = ({ onGameEnd }: Props)
```

Так будет на один импорт меньше.

2024-09-10 20:44 UTC, Gyxer513 commented on packages/client/src/game/ui/GameClient.tsx
>        ctx.clearRect(0, 0, Game.Size.width, Game.Size.height)
Компонент получился перегруженным, можно попробовать создать функцию типа такой 

```
 const drawGameElements = (canvas: HTMLCanvasElement, ctx: CanvasRenderingContext2D) => {
    background.draw({ canvas, ctx }, backgroundOptions)
    quickTools.draw({ canvas, ctx })
    borders.draw({ canvas, ctx })
    craftTools.draw({ canvas, ctx })
    player.draw({ canvas, ctx })
    player.update({ canvas, ctx })
    craftDialog.draw({ canvas, ctx })
    notifications.draw({ canvas, ctx })
    receiptBook.draw({ canvas, ctx })
    winConditionDialog.draw({ canvas, ctx })
  }
```

При этом можно вынести ее за компонент и деструктурировать хуки.

2024-09-11 09:19 UTC, RanelGM commented on packages/client/src/game/ui/GameClient.tsx
>        ctx.clearRect(0, 0, Game.Size.width, Game.Size.height)
Вынес в отдельную функцию, стало почище

За компонент вынести не получится, т.к. используются хуки. В целом, предлагаю в отдельный хук пока что не выносить, т.к. по задумке этот компонент является точкой входа для всех других хуков и место их инициализации

2024-09-11 09:20 UTC, RanelGM commented
> Есть замечание на твое усмотрение. При открытии шпаргалки во время смешивания ингредиентов, шпаргалка закрывает попап со смешиванием, на мой взгляд это не удобно. Можно в этой итерации оставить так, если быстро это не пофиксить.


Этот момент, к сожалению, быстро не пофиксить, поэтому да, пока что пусть остается так в этой итерации

2024-09-11 09:24 UTC, Gyxer513 approved these changes
Отличная работа.

2024-09-11 13:22 UTC, kyzinatra commented on packages/client/src/core/utils/constants.ts
>    ArrowLeft: 'ArrowLeft',
Можно лучше: константы контролов лучше называть по их смыслу а не по клавише. Так будет чуть яснее и в случае смены клавиши не надо будет все менять. То есть не `A: "KeyA"`, а `LeftMove: "KeyA"`

2024-09-11 13:24 UTC, kyzinatra commented on packages/client/src/game/constants/receipts.ts
> +  [IngredientNames.HollyDry]: {
Мне кажется тут не нужно обобщать тип. Можно оставить константу вообще без типа. ts сам выведет более точный тип, чем `Record<string, Receipt>`

2024-09-11 13:24 UTC, kyzinatra commented on packages/client/src/game/constants/receipts.ts
> +  ...IngredientReceipts,
По аналогии

2024-09-11 13:34 UTC, kyzinatra approved these changes
Отличная работа! Хорошие комментарии с кодом, все вынесено по отдельным папкам. Есть несколько мелких моментов, которые я бы улучшил, но в целом все очень хорошо. Лично по моему мнению это одна из самых сложных частей работы и вы отлично с ней справились!

2024-09-11 15:26 UTC, merged