ALC-31 service worker
Thalassa666/Alchemica pull request #24
Opened 2024-09-11 08:14 UTC by Thalassa666

### Какую задачу решаем
добавлен SW 
исправлен div в кнопке на span
отформатированы стили prettier

2024-09-11 12:41 UTC, Gyxer513 requested changes
К сожалению, работа отклоняется от проверки, ProtectedRoute не дает зайти на страницу игры. 

Можно сделать мердж с develop или удалить компонент.

2024-09-11 13:38 UTC, Thalassa666 commented
слила с dev

2024-09-11 14:22 UTC, Gyxer513 approved these changes
Отличная работа, SW отрабатывает, все модули работают без интернета.

2024-09-12 14:13 UTC, kyzinatra commented on packages/client/src/sw.js
> +]
Надо исправить: так как у вас SPA приложение вы кэшируете на любой маршрут `index.html` и не кэшируете статику `css`, `js` файлы и картинки. Необходимо взять файлы из build и вписывать их в урлы для кэша

2024-09-12 14:14 UTC, kyzinatra commented on packages/client/src/sw.js
> +        }
Можно лучше: стоит подумать об инвалидации кэша и сделать white list с теми маршрутами, которые имеет смысл кэшировать, а не делать это везде подрял

2024-09-12 14:15 UTC, kyzinatra approved these changes
Отличная работа! Вы отлично потрудились над service workerом, но сейчас не очень корректно работает обработчик `install`. Стоит его поправить и после этого ваша работа будет принята. Если у вас возникнут вопросы по этой теме можете задать их тэгнув меня тут @kyzinatra

2024-09-13 05:33 UTC, Thalassa666 commented
исправила

2024-09-13 19:02 UTC, kyzinatra commented
Вы отлично потрудились.
Поздравляю! Ваша работа принята.
Удачного дальнейшего обучения.

2024-09-14 15:53 UTC, merged