Feature/alc 43/add leaderboard api and connect it to ui
Thalassa666/Alchemica pull request #30
Opened 2024-10-05 18:25 UTC by RanelGM

### Какую задачу решаем
- Добавлен API для Лидерборда (получение списка результатов и отправка результата)
- API подключен к UI (отображение списка, состояния ошибок и загрузки)

2024-10-07 10:48 UTC, Gyxer513 approved these changes
Отличная работа! У меня нет замечаний.

2024-10-07 19:12 UTC, MikeDevice requested changes
Ты большой молодец! Всё классно. Я написал, что можно сделать лучше. Ставлю реджект только из-за одной малюсенькой, но важной проблемы с типизацией.

2024-10-07 19:12 UTC, MikeDevice commented on packages/client/src/components/Leaderboard/LeadersListItem.tsx
> +  return { name: `Успешно сдавший`, level: 'fourth' }
1. Красавчик, что используешь `_` как разделитель нулей!

**Можно лучше:** ты дублируешь все ифаки. То есть, если тебе придётся изменить структуру объекта `{name, level}`, то тебе придётся в каждой строке менять это. Это неудобно и можно забыть или ошибиться.

Самый простой способ обезопаситься: добавить функции возвращаемое значение:

```diff
- const getRang = (score: number) => {
+ const getRang = (score: number): { name: string; level: string; } => {
```

Но можно пойти дальше и сделать прям конфиг:

```tsx
type Level = 'first' | 'second' | 'third' | 'fourth'
type Score = { name: string; value: number; }

const scoreConfig: Record<Level, Score> = {
   first: { name:  '...', value: 10_000},
   ...
}

const getRang = (score: number) => {
   return /** ищешь из scoreConfig максимально близкий value **/
}
```

Такой код сложнее с одной стороны, но с другой, его проще масштабировать. Представь, если бы левелов было не 4, а 500, или 1000. Ты бы просто задолбался копипастить одно и то же миллион раз

2024-10-07 19:12 UTC, MikeDevice commented on packages/client/src/components/Leaderboard/LeadersListItem.tsx
> +        />
**Можно лучше** на практике практически всегда добавляется две картинки: оригинальная и точно такая же, но в два раза больше. Она нужна для особо чётких экранов, как ретина. Вот тут можно узнать подробнее https://htmlacademy.ru/blog/html/retina

2024-10-07 19:12 UTC, MikeDevice commented on packages/client/src/components/Leaderboard/LeadersListItem.tsx
> +            styles[`skill--${rang.level}`]
**Можно лучше** если использовать нижнее подчёркивание для стилей, то скобки не нужны будут)

2024-10-07 19:12 UTC, MikeDevice commented on packages/client/src/components/Leaderboard/styles.module.scss
> +    background-image: url('../../assets/images/icons/skill-4-pic.png');
то же, что и выше я говорил про ретину

2024-10-07 19:12 UTC, MikeDevice commented on packages/client/src/core/api/Leaderboard.ts
> +    this.url = url + slug
**можно лучше** когда ты просто склеиваешь, есть вероятность, что может появиться где-то лишний слеш, например вот так: `https://google.com/ + '/hello' = https://google.com//hello`.

Чтобы такого точно не было, можно использовать класс URL https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

2024-10-07 19:12 UTC, MikeDevice commented on packages/client/src/core/api/Leaderboard.ts
> +      },
**можно лучше** чтобы не копипастить везде одно и тоже, как `'Content-Type': 'application/json'`, можно написать базовый класс `API`, у которого был бы метод `request`, который содержал бы общие части

2024-10-07 19:12 UTC, MikeDevice commented on packages/client/src/core/store/reducers/leaderboard.reducer.ts
> +      return rejectWithValue(error)
**можно лучше:** сделать базовый thunk, который бы содержал try catch. так не будет дублирования кода

2024-10-07 19:12 UTC, MikeDevice commented on packages/client/src/pages/PlayGame/PlayGame.tsx
> +    if (step === 'won' && endedAt && startedAt && user) {
**можно лучше** дублируешь проверку на won. можно просто сохранить в переменную и использовать её в двух местах

2024-10-07 19:12 UTC, MikeDevice commented on packages/client/src/pages/PlayGame/PlayGame.tsx
> +          user: user as IUser,
**Нужно исправить** вот так не нужно делать. Приведение типов это само по себе не очень хорошая вещь. А тут ты приводишь тип к интерфейсу. (то, что с ай начинается). Если бы не эта `I` я бы проигнорил. А так исправь, пожалуйста, потому что интерфейсы должны использоваться только для ООП.

2024-10-08 17:38 UTC, RanelGM commented on packages/client/src/components/Leaderboard/LeadersListItem.tsx
> +        />
Дело в том, что url берётся от данных пользователя с ручки auth/user
Оттуда приходит только 1 изображение, поэтому нет возможности поставить разные в зависимости от дисплея

2024-10-08 17:40 UTC, RanelGM commented on packages/client/src/components/Leaderboard/LeadersListItem.tsx
> +            styles[`skill--${rang.level}`]
Не уверен, что получится (по крайней мере у меня не вышло), т.к. тут вставка расчетного значения  rang.level, а не просто текст "rang.level"

2024-10-08 17:41 UTC, RanelGM commented on packages/client/src/components/Leaderboard/styles.module.scss
> +    background-image: url('../../assets/images/icons/skill-4-pic.png');
Сгенерировано через AI, поэтому нет возможности вытащить доп-но для ретины

2024-10-08 17:42 UTC, RanelGM commented on packages/client/src/core/api/Leaderboard.ts
> +    this.url = url + slug
Согласен, но сейчас исправить без полного изменения прочих api и их BASE_URL не получится, т.к. в BASE_URL в т.ч. заложено /api/v2 , которое будет откинуто через new URL (relative URLs)

2024-10-08 17:43 UTC, RanelGM commented on packages/client/src/core/api/Leaderboard.ts
> +      },
Согласен, но решил поддерживать стиль команды, чтобы потом проще было всё разом искать для рефакторинга, при необходимости

2024-10-08 17:43 UTC, RanelGM commented on packages/client/src/core/store/reducers/leaderboard.reducer.ts
> +      return rejectWithValue(error)
Аналогично - поддержание стиля команды, чтобы потом проще было отрефакторить

2024-10-08 17:57 UTC, RanelGM commented
Внёс изменения по критическим моментам

По некоторым моментам, которые некритические - на текущий момент не вносил изменений, чтобы поддержать единый стиль по команде и в будущем можно было единоразово всё зарефакторить (и удобнее было бы сравнить что получается)

2024-10-09 22:38 UTC, MikeDevice approved these changes
Идеально! Спасибо!

2024-10-10 16:45 UTC, merged