Feature/alc 25/error boundary
Thalassa666/Alchemica pull request #6
Opened 2024-08-28 16:37 UTC by Thalassa666

### Какую задачу решаем
Добавить [ErrorBoundary](https://legacy.reactjs.org/docs/error-boundaries.html).

При возникновении ошибки в компоненте приложение не падает, ошибка обработана в ErrorBoundary.

2024-08-28 20:15 UTC, Gyxer513 requested changes

2024-08-28 20:15 UTC, Gyxer513 commented on packages/client/src/core/router/index.tsx
> +      <ErrorBoundary FallbackComponent={ErrorFallback}>
Кажется, оборачивать каждый роут в этот компонент плохая идея. Нужно обернуть им все приложение.

2024-08-31 13:51 UTC, Thalassa666 commented
@Gyxer513 пробовала обернуть весь App , не получилось. предлагаю пока что оставить такой вариант, не тратить сейчас время на это.

2024-08-31 17:16 UTC, Gyxer513 approved these changes
Отличная работа.

2024-08-31 17:21 UTC, merged